export const listData = [
  {id: 1, text: "Banco de Dados II - DP", date: "Quarta-feira", hour: "9h30 - 13h",
objective: "Apresentar recursos avançados para criação de aplicativos com Banco de dados.", ement: "Tipos de Junções (join). Subconsultas (Subqueries). Criação, implementação e utilização de procedimentos armazenados (stored procedures), gatilhos (triggers), funções, cursores, visões (view). Linguagem de Controle de Dados. Transações. Bancos de dados orientados a objetos. Bancos de dados multimídia."},
  {id: 2, text: "Desenvolvimento para Servidores I - DP", date: "Segunda-feira", hour: "9h30 - 13h",  objective: "Esta disciplina fornecerá uma visão geral da linguagem script PHP associado a um gerenciador de banco de dados que utilize a linguagem SQL e como usar essas tecnologias para gerar sites dinâmicos. Introduzir práticas de codificação seguras", ement:"PHP histórico e emprego. Instalação e configuração básica do PHP e um IDE. Sintaxe básica do PHP. Usando o PHP como um mecanismo de modelo simples. Panorama das melhores práticas com PHP. Conceitos de programação HTTP. Codificação de caracteres. Localidades, fusos horários e funções de tempo. Strings. Uso de Array e funções de matriz. Orientação a objetos em PHP (Classes, objetos, herança, encapsulamento, polimorfismo, agregação, composição e métodos). Tratamento de exceções de erro. Arquitetura do lado do servidor. Manipulação de dados postados. Enviando e-mail. Sessões e autenticação. Cookies. Arquivo manuseio e armazenamento de dados em arquivos de texto. Gerenciador de banco de dados e suas funções. Frameworks. Web Services, API, RSS, JSON e Ajax. Hospedagem compartilhada."},
  {id: 3, text: "Desenvolvimento para Servidores II", date: "Quinta-feira", hour: "9h30 - 13h",
  objective: "Desenvolver um site completo de e-commerce ou outro tipo de negócio na Internet usando uma linguagem apropriada a servidores, banco de dados e padrões de projeto.", ement:"Conceitos e evolução das tecnologias de programação de servidores. Recursos da linguagem escolhida para servidores na Internet. Padrões de projetos. Integração com sistemas (Google Maps API, Twitter, entre outros)"},
  {id: 4, text: "Desenvolvimento para Dispositivos Movéis I", date: "Segunda-feira", hour: "9h30 - 13h",  objective: "Apresentar as tecnologias de desenvolvimento de aplicativos para dispositivos móveis.", ement:"Introdução e conceitos. Recursos disponíveis para dispositivos móveis na linguagem de marcação de textos. Uso de algum ambiente de desenvolvimento: configuração do ambiente; emulação de dispositivos móveis nos computadores pessoais; interface gráfica; serviços disponíveis; banco de dados nos dispositivos. Desenvolvimento de aplicações que utilizam dados de geolocalização. Integração entre sistemas remotos."},
  {id: 5, text: "Negócios, Marketing e Eletrônicos", date: "Quarta-feira", hour: "9h30 - 13h",  objective: "Apresentar e discutir as questões do marketing na era da Internet. Abordar as principais estratégias, ações, ferramentas e mídias presentes na Web.", ement:"Conceitos de marketing e de marketing digital. O comportamento do consumidor on-line. Marketing de conteúdo. Marketing nas mídias sociais. E-mail marketing. Marketing viral. Publicidade on-line. Pesquisa de marketing on-line. Marketing e os negócios na Internet. Estudos de caso."},
  {id: 6, text: "Projeto de Prototipagem e Testes de Usabilidade", date: "Sábado", hour: "9h30 - 13h",  objective: "Aprofundar os conceitos de design da usabilidade e métodos de ensaio para mídia interativa. Usabilidade baseada na adaptação de design de interface para uma experiência do usuário mais eficaz. Apresentar e usar diferentes métodos e ferramentas de prototipagem para explorar com os colegas de equipe ou clientes: conceitos de design, comunicação e testes de usabilidade", ement:"Conceitos, métodos de prototipagem e ferramentas de teste de protótipos. Conceitos de usabilidade e estratégias de design. Métodos de teste de usabilidade. Planejamento de teste de usabilidade. Recrutamento. Projeto de usabilidade. Plano de teste. Sessão de teste de usabilidade. Análise de dados. Comunicação dos resultados. Variação de técnicas."},
  {id: 7, text: "Tópicos Especiais II", date: "Sexta-feira", hour: "9h30 - 13h",  
  objective: "Apresentar tecnologias ainda não estudadas ou aprofundar algum tema já visto definido pela coordenadoria do curso em cada unidade.", ement:"Recursos e aplicações da tecnologia escolhida."}
]